feature(rjy): add rough framework of obs encoder
PaParaZz1/DI-card pull request #2
Opened 2023-07-18 09:22 UTC by nighood

2023-07-24 04:24 UTC, PaParaZz1 requested changes

2023-07-24 04:24 UTC, PaParaZz1 commented on genshin_card_env.py
> +    encoded_obs = obs_encoder(batch_obs, batch_last_action)
assert something in `encoded_obs`

2023-07-24 04:24 UTC, PaParaZz1 commented on obs_encoder.py
> +        self.init_merge_flag = False
why name it to `init_merge_flag`

2023-07-24 04:24 UTC, PaParaZz1 commented on obs_encoder.py
> +            self.obs_merge = VectorMerge(input_sizes=obs_input_sizes, output_size=256)
define the instance of `nn.Module` in `__init__`

2023-07-24 04:24 UTC, PaParaZz1 commented on obs_encoder.py
> +import treetensor.torch as ttorch
add unittest for file, especially taking loss back propogration into consideration

2023-07-24 04:24 UTC, PaParaZz1 commented on obs_encoder.py
> +            global_obs = torch.cat([
use one-hot encoding, then concatanate

2023-07-26 02:37 UTC, puyuan1996 commented on genshin_card_env.py
> +from obs_encoder import ObservationEncoder
优化import顺序

2023-07-26 02:37 UTC, puyuan1996 commented on genshin_card_env.py
> +        max_card_num: int = 30,     # The deck contains 30 action cards
yapf format

2023-07-26 02:37 UTC, puyuan1996 commented on genshin_card_env.py
> +    assert encoded_obs.shape == (batch_size, embedding_size), 'shape of encoded_obs wrong'
'shape of encoded_obs wrong' -> 完整的句子

2023-07-26 02:37 UTC, puyuan1996 commented on genshin_card_env.py
> +    batch_obs = to_device([obs.tensor() for i in range(batch_size)],'cuda')
batch_obs 由不同的 sample 组成

2023-07-26 02:37 UTC, puyuan1996 commented on obs_encoder.py
> +    def __init__(self, input_size, output_size=256, hidden_size=64):
添加type hint

2023-07-26 02:37 UTC, puyuan1996 commented on obs_encoder.py
> +    def __init__(self, input_size, output_size=256, hidden_size=64):
为每个类添加overview comments

2023-07-26 02:37 UTC, puyuan1996 commented on obs_encoder.py
> +        # sub-obs
更加详细的注释

2023-07-26 02:37 UTC, puyuan1996 commented on obs_encoder.py
> +        supporter_other_info_list = []
或许可以换成
```
processed_obs_lists = {
    "global": [],
    "dice": [],
    "character": [],
    "skill": [],
    "card": [],
    "summoner": [],
    "supporter": [],
    "character_other_info": [],
    "skill_other_info": [],
    "card_other_info": [],
    "summoner_other_info": [],
    "supporter_other_info": [],
}
```

2023-07-26 02:37 UTC, puyuan1996 commented on obs_encoder.py
> +        supporter_other_info_obs = torch.stack(supporter_other_info_list, dim=0)
在使用dict存储信息后，这里可以修改为
```
processed_obs_stacks = {}
for key in processed_obs_lists.keys():
    processed_obs_stacks[key] = torch.stack(processed_obs_lists[key], dim=0)
```

2023-07-26 02:37 UTC, puyuan1996 commented on test_obs_encoder.py
> +        assert encoded_obs.shape == (B, embedding_size), 'shape of encoded_obs wrong'
assert信息写完整一些，并给出报错后给用户的排查方案

2023-07-26 02:45 UTC, puyuan1996 commented on obs_encoder.py
> +        ], dim=1)
```
# 先在 __init__中定义：

self.encoders = {
    'global': self.global_encoder,
    'dice': self.dice_encoder,
    'character': self.character_encoder,
    'skill': self.skill_encoder,
    'card': self.card_encoder,
    'summoner': self.summoner_encoder,
    'supporter': self.supporter_encoder
}

# 然后将上面的代码修改为：

# Handle global and dice separately as they don't need concatenation
encoded_obs['global_obs'] = self.encoders['global'](new_obs['global_obs'])
encoded_obs['dice_obs'] = self.encoders['dice'](new_obs['dice_obs'])

# Loop over the rest of the keys
for key in ['character', 'skill', 'card', 'summoner', 'supporter']:
    encoded_obs[f'{key}_obs'] = torch.cat([
        self.encoders[key](new_obs[f'{key}_obs']),
        new_obs[f'{key}_other_info_obs']
    ], dim=1)
```

2023-07-26 06:10 UTC, PaParaZz1 commented on obs_encoder.py
> +        # sub-obs
全面的注释先不加了哈，因为可能还要修改，只加一写关键的注释就行

2023-07-26 15:46 UTC, puyuan1996 commented on obs_encoder.py
> +        Encoder that encodes dice_obs.
每个overview里面关于obs的类别或许可以解释再详细一点，达到对于不熟悉七圣召唤游戏的人也能大概知道其含义。

2023-07-27 02:49 UTC, puyuan1996 commented on obs_encoder.py
> +        self.obs_merge = VectorMerge(input_sizes=obs_input_sizes, output_size=output_size)
增加注释

2023-08-01 06:07 UTC, merged